joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_01
    - joint_02
    - joint_03
    - fake_joint_04
    - fake_joint_05
    - fake_joint_06
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_01: {trajectory: 0.1, goal: 0.05}
    joint_02: {trajectory: 0.1, goal: 0.05}
    joint_03: {trajectory: 0.1, goal: 0.05}
    fake_joint_04: {trajectory: 0.1, goal: 0.05}
    fake_joint_05: {trajectory: 0.1, goal: 0.05}
    fake_joint_06: {trajectory: 0.1, goal: 0.05}
  stop_trajectory_duration: 0.5
  state_publish_rate: 25
  action_monitor_rate: 10
